version: '3'
services:
  web:
    build:
      context: ./docker/construct_web   # Where Dockerfile 
      dockerfile: Dockerfile            # Dockerfile's name
    image: nn-web               # image name
    container_name: nn-web      # container name
    ports:
      - 80:80


  app:
    build:
      context: ./docker/construct_app   # Where Dockerfile
      dockerfile: Dockerfile            # Dockerfile's name
    image: oee                  # image name
    container_name: oee         # container name
    ports:
      - 3000:3000
    volumes:                    # mount dir
      - ./coderunner:/src
      - /var/run/docker.sock:/var/run/docker.sock
   ## If you use macOS   -> /usr/local/bin/docker
   ## If you use CentOS  -> /usr/bin/docker
      - /usr/bin/docker:/usr/bin/docker 


    command: [sh, -c, npm install && node app.js]
